#-----------------------------
#
#Copyright by SkyLine, 2024 :)
#
#-----------------------------

name: build_NET_pipeline
on:
  push:
    branches: 
      - main
jobs:
  build:

    runs-on: ubuntu-latest
    steps: 
    - name: Copy repos
      uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4.0.0
      #with:
        #dotnet-version: '8.0.101'
    - name: Build App
      run: dotnet build

  deploy: 

    runs-on: ubuntu-latest
    needs: [build]
    steps:

    - name: Copy repos
      uses: actions/checkout@v4   
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4.0.0
      #with:
      #dotnet-version: '8.0.101'
    - name: Build App
      run: dotnet build
    
    - name: Enable SSH Redirect Port
      uses: stoneydavis/ssh-port-forward-action@v1.0.0
      with:
        ssh_key: ${{ secrets.SSH_PUBLIC_VM_PRIVATE_KEY }}
        ssh_host: ${{ secrets.SSH_PUBLIC_HOST }}
        ssh_port: 22000
        ssh_user: ${{ secrets.SSH_PUBLIC_VM_USERNAME }}
        local_port: 22000
        remote_host: 192.168.100.2
        remote_port: 22
        
    - name: Copy Project file to Prod Server
      run: |
          nc -zv 127.0.0.1 22000
          echo "${{secrets.SSH_PRIVATE_VM_PRIVATE_KEY}}" > ./.key;
          chmod 0400 ./.key;
          ssh-keygen -y -e -f .key
          hostname
          rm user_key
          rsync -e "ssh -i .key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 22000" -av --exclude '.*' $(pwd)/ ${{ secrets.SSH_PRIVATE_VM_USERNAME }}@127.0.0.1:/home/${{ secrets.SSH_PRIVATE_VM_USERNAME }}/WEBSERVER/
          
  #  - name: build docker container
  #    uses: appleboy/ssh-action@v1.0.3
  #    with:
  #      host: 127.0.0.1
  #      username: ${{ secrets.SSH_PRIVATE_VM_USERNAME }}
  #      key: ${{  secrets.SSH_PRIVATE_VM_PRIVATE_KEY  }}
  #      port: 22000
  #      script: |
  #          hostname
  #          nc -zv 127.0.0.1 22000
  #          docker stop WebContainer && docker rm WebContainer && sudo docker build . -t webimage && docker run --name WebContainer --restart always -d -p 9595:9595 webimage
  #          cd ${{ secrets.SSH_PATH_PROJECT_PRIVATE_VM }}      
    - name: build docker image and restart container
      run: |
          ssh -tt -i .key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 22000 ${{ secrets.SSH_PRIVATE_VM_USERNAME }}@127.0.0.1 "docker stop WebContainer && docker rm WebContainer && sudo docker build . -t webimage && docker run --name WebContainer --restart always -d -p 9595:9595 webimage"

             #   hostname
              #  docker stop WebContainer && docker rm WebContainer && sudo docker build . -t webimage && docker run --name WebContainer --restart always -d -p 9595:9595 webimage
              #  cd ${{ secrets.SSH_PATH_PROJECT_PRIVATE_VM }}
