#-----------------------------
#
#Copyright by SkyLine, 2024 :)
#
#-----------------------------

name: build_NET_pipeline
on:
  push:
    branches: 
      - main
jobs:
  build:

    runs-on: ubuntu-latest
    steps: 
    - name: Copy repos
      uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4.0.0
      #with:
        #dotnet-version: '8.0.101'
    - name: Build App
      run: dotnet build

  deploy: 

    runs-on: ubuntu-latest
    needs: [build]
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Run command on remote server
      uses: stoneydavis/ssh-port-forward-action@v1.0.0
      with:
        ssh_key: ${{ secrets.SSH_PUBLIC_VM_PRIVATE_KEY }}
        ssh_host: ${{ secrets.SSH_PUBLIC_HOST }}
        ssh_port: 22000
        ssh_user: ${{ secrets.SSH_PUBLIC_VM_USERNAME }}
        local_port: 22000
        remote_host: 192.168.100.2
        remote_port: 22
      
    - name: Check Port
      run: |
          nc -zv 127.0.0.1 22000

    #- name: copy file via ssh key
    #  uses: appleboy/scp-action@v0.1.7
    # with:
    #    host: 127.0.0.1
    #    username: ${{ secrets.SSH_PRIVATE_VM_USERNAME }}
    #    port: 22000
    #    key: ${{ secrets.SSH_PRIVATE_VM_PRIVATE_KEY }}
    #    source: ./
    #    target: ~/WEBSERVER/
