#------------------------------
#
#Copyright by SkyLine, 2024.
#
#------------------------------

name: build_NET_pipeline
on:
  push:
    branches: 
      - main
jobs:
  build:

    runs-on: ubuntu-latest
    steps: 
    - name: Copy repos
      uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4.0.0
      #with:
        #dotnet-version: '8.0.101'
    - name: Build App
      run: dotnet build

  deploy: 

    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run command on remote server
      uses: selfagency/ssh-port-forward-action@v1.0.5
      with:
        ssh-key: ${{ secrets.SSH_PRIVATE_VM_PRIVATE_KEY }}
        ssh-host: ${{ secrets.SSH_PUBLIC_HOST }}
        ssh-port: 22
        ssh-user: ${{ secrets.SSH_PRIVATE_VM_USERNAME }}
        local-port: 3333
        remote-host: 192.168.100.2
        remote-port: 22
    - run: echo "123" > remote_ssh_text.txt
